projects:
  reactamplifyworkshop:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: j45rwe6oxnd3tjsbubjrlseilu
      endpoints:
        prod: >-
          https://lryoip5kireitcjsqqlg5mprha.appsync-api.us-east-1.amazonaws.com/graphql
